theme: jekyll-theme-slate
title: Unmanned Aircraft System for Disaster Response
description: Our goal is to begin a framework for developing low cost Unmanned Aircraft Systems to aid First Responders in Disaster Response scenarios.
